arc: Fix build error with GDB 7.12
Upstream patch:

    f2f45a7 Sync proc_service definition with GLIBC

changed declaration of ps_get_thread_area, hence it's definitions in ARC code
should be updated accordingly, to avoid build error:

../gdb/gdbserver/linux-arc-low.c:459:1: error: conflicting types for ‘ps_get_thread_area’
 ps_get_thread_area (const struct ps_prochandle *ph, lwpid_t lwpid, int idx,
 ^~~~~~~~~~~~~~~~~~
In file included from ../gdb/gdbserver/linux-low.h:24:0,
                 from ../gdb/gdbserver/linux-arc-low.c:41:
../gdb/gdbserver/gdb_proc_service.h:110:17: note: previous declaration of ‘ps_get_thread_area’ was here
 extern ps_err_e ps_get_thread_area (struct ps_prochandle *,
                 ^~~~~~~~~~~~~~~~~~

Signed-off-by: Anton Kolesov <Anton.Kolesov@synopsys.com>